In [3]:
import numpy as np

In [24]:
# a null vector of size 10 but the fifth value which is 1
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [12]:
# a vector with values ranging from 10 to 49
ns=np.arange(10,50)
ns

40

In [20]:
#a 3x3 matrix with values ranging from 0 to 8
import random
ns=np.random.randint(0,8,(3,3))
ns

array([[0, 7, 7],
       [1, 1, 5],
       [3, 0, 0]])

In [22]:
#indices of non-zero elements from [1,2,0,0,4,0]
non_zero=np.array([1,2,0,0,4,0])
np.nonzero(non_zero)

(array([0, 1, 4], dtype=int64),)

In [13]:
# a 10x10 array with random values and find the minimum and maximum value
import random
np.random.seed(0)
x=np.random.randn(1,10,10)
print(x)
print("max value:",np.max(x))
print("min value :",np.min(x))



[[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799
   -0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
  [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323
    0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
  [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462
   -1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877]
  [ 0.15494743  0.37816252 -0.88778575 -1.98079647 -0.34791215
    0.15634897  1.23029068  1.20237985 -0.38732682 -0.30230275]
  [-1.04855297 -1.42001794 -1.70627019  1.9507754  -0.50965218
   -0.4380743  -1.25279536  0.77749036 -1.61389785 -0.21274028]
  [-0.89546656  0.3869025  -0.51080514 -1.18063218 -0.02818223
    0.42833187  0.06651722  0.3024719  -0.63432209 -0.36274117]
  [-0.67246045 -0.35955316 -0.81314628 -1.7262826   0.17742614
   -0.40178094 -1.63019835  0.46278226 -0.90729836  0.0519454 ]
  [ 0.72909056  0.12898291  1.13940068 -1.23482582  0.40234164
   -0.68481009 -0.87079715 -0.57884966 -0.311552

In [18]:
# a random vector of size 30 and find the mean value
np.random.seed(1)
y=np.random.randn(3,10)
print(y)
print("mean is:",np.mean(y))

[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
   1.74481176 -0.7612069   0.3190391  -0.24937038]
 [ 1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944 -1.09989127
  -0.17242821 -0.87785842  0.04221375  0.58281521]
 [-1.10061918  1.14472371  0.90159072  0.50249434  0.90085595 -0.68372786
  -0.12289023 -0.93576943 -0.26788808  0.53035547]]
mean is: -0.0599389106556233
2
